# Generated by Django 4.1.1 on 2022-09-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='basicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Importe_asociado', models.CharField(max_length=60)),
                ('Importe_gastado', models.IntegerField()),
                ('Fecha_importe', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='curso',
        ),
        migrations.DeleteModel(
            name='entregable',
        ),
        migrations.DeleteModel(
            name='estudiante',
        ),
        migrations.DeleteModel(
            name='profesor',
        ),
    ]
