# Generated by Django 4.1.1 on 2022-09-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_basicos_delete_curso_delete_entregable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Importe_asociado', models.CharField(max_length=60)),
                ('Importe_gastado', models.IntegerField()),
                ('Fecha_importe', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='varios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Importe_asociado', models.CharField(max_length=60)),
                ('Importe_gastado', models.IntegerField()),
                ('Fecha_importe', models.DateField()),
            ],
        ),
    ]
